# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContactList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContactList
  pod 'SwiftKeychainWrapper', '~> 4.0'
  pod 'SwiftGen', '~> 6.0'

  target 'ContactListTests' do
    inherit! :search_paths
    # Pods for testing
  pod 'SwiftKeychainWrapper', '~> 4.0'
  pod 'SwiftGen', '~> 6.0'

  end

  target 'ContactListUITests' do
    # Pods for testing
  pod 'SwiftKeychainWrapper', '~> 4.0'
  pod 'SwiftGen', '~> 6.0'

  end

end

target 'ContactList_MOCK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContactList_MOCK
    pod 'SwiftKeychainWrapper', '~> 4.0'
    pod 'SwiftGen', '~> 6.0'
end
